project_name: Language Randomizer

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
      
nfpms:
  - maintainer: F. Talha Altinel <talhaaltinel@hotmail.com>
    description: CLI for quickly building & zipping lambda artifacts
    homepage: https://github.com/MrWormHole/artificer
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: "asc"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"