on:
  push:
    branches: [main]
    tags:
      - 'v*'

name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
